### ISSUE TITLE
JS Datetime

### ISSUE THREAD

**Issue by JStika** [saleemkce/timeonsite#3]
I've still question.

Example:
I'm testing on windows 10, xampp, PHP diresctive is date.timezone: Europe/Prague.
I got data saved to database -2 hours from JS Datetime.

I'm living in Kosice, Slovakia - +1 GTM. Now is summer time.

JS Datetime funtion returns CET time, I want current time returned by browser. How can I correct this problem?

**Comment by JStika** [comment]
[WTZ2bForRebellion.zip](https://github.com/saleemkce/timeonsite/files/4468534/WTZ2bForRebellion.zip)
Please, look at my very old js script, when I open in Chrome browser, I see exactly current time, the same as my system time from my PC.......

**Comment by saleemkce** [comment]
We use the date time features provided by Javascript API directly. For internal purposes, we are using UTC/ISO format as required. Also, our goal is to capture time on page/time on site with precision not timezone information.

```
Tos.getTimeOnPage();  // call anytime to get current data
{
  "TOSId": 14368825848828906,
  "TOSSessionKey": "3847158753993774774675",
  "TOSUserId": "anonymous",
  "URL": "https://saleemkce.github.io/timeonsite/",
  "title": "Timeonsite Tracker | Real-time demo",
  "entryTime": "2020-04-22 07:19:36.259",
  "currentTime": "2020-04-22 07:22:24.606",
  "timeOnPage": 90,
  "timeOnPageTrackedBy": "second",
  "timeOnSite": 37,
  "timeOnPageByDuration": "0d 00h 01m 30s",
  "timeOnSiteByDuration": "0d 00h 00m 37s",
  "trackingType": "tos"
}
```

We shouldn't modify the data returned by **_timeonsitetracker.js_** directly. You may use timezone conversions or modification in backend or modify the way you store the data in DB timestamps as you prefer. Customizing the data in [visual](https://github.com/saleemkce/visual), reporting tool is also another option. Closing the thread as this is customization/behavior and not an issue.
