### ISSUE TITLE
Timeonsite extend session issue

### ISSUE THREAD

**Issue by saleemkce** [saleemkce/timeonsite#5]
But, another issue:
    if (tosSessionManager === 1) {
        Tos.startSession("user_"+tosCustomData.userId);
        Tos.extendSession({$cookieLifeTime|noescape});
	} else if (tosSessionManager === 2) {
        Tos.endSession();
	}

Variable $cookieLifeTime is cookie life time from  Nette framework (+14 days).
If I use Tos.extendSession({$cookieLifeTime|noescape}); I see in console current datetime and not datetime + 14 days.

_Originally posted by @JStika in https://github.com/saleemkce/timeonsite/issues/4#issuecomment-613969903_

**Comment by saleemkce** [comment]
what value do you pass inside **_extendSession()_** function?

For example for extending to 10 days, you will give

`Tos.extendSession(864000);`  //10 days time period in seconds

**Comment by JStika** [comment]
This value is 1209600;

**Comment by saleemkce** [comment]
Then it's

`Tos.extendSession(1209600); //14 days time period in seconds`

>  I see in console current datetime and not datetime

Can you show some screen shot or sample data to describe the problem?

**Comment by JStika** [comment]
From console log: Session extended till Wed Apr 29 2020 13:30:32 GMT+0200 (Středoevropský letní čas)

**Comment by JStika** [comment]
Ups, it's correct. Pardon.

**Comment by saleemkce** [comment]
Great! And please close the issue if it's fine.

**Comment by JStika** [comment]
Im sorry, I'm blind yet.:)

**Comment by JStika** [comment]
Where? I cannot close this.

**Comment by saleemkce** [comment]
No problem. I'll close it.
