### ISSUE TITLE
I have a request

### ISSUE THREAD

**Issue by JStika** [saleemkce/timeonsite#6]
Hi,

I cannot add a new PR.
I have a request. 
Are you willing to add new items like IP and country?
E.g.: 
https://stackoverflow.com/questions/37111788/how-to-get-user-country-name-from-user-ip-address-in-php

**Comment by saleemkce** [comment]
```
http://api.db-ip.com/addrinfo?api_key=<your api key>&addr=<ip address>
{
  "address": "116.12.250.1",
  "country": "SG",
  "stateprov": "Central Singapore",
  "city": "Singapore"
}
```

```
if (TimeOnSiteTracker) {
        Tos = new TimeOnSiteTracker();
}

$.get('http://api.db-ip.com/addrinfo?api_key=<your api key>&addr=<ip address>', function(data) {
    // console.log(data.country)
	
	Tos.setCustomData({
	    country: data.country,
	    city: data.city
	});
});
```

This is what you want to track from frontend, right?

**Comment by JStika** [comment]
Yes, that it's.

Thank you for the idea.

**Comment by saleemkce** [comment]
No, it won't slow down _**timeonsitetracker.js**_ but it's a time-critical component. It's allowed.

var customData = {
     browserName: Chrome,
     majorVersion: 80
};
Tos.setCustomData(customData );

Calling _[Tos.setCustomData()](https://saleemkce.github.io/timeonsite/docs/index.html#setting-custom-data)_ is a simple setter method which can accept decent amount of key/value pair data and sent to server without any overhead.

_**Note: you have to adjust backend script to accept custom data in table INSERT statements if you are using RDMBS. In case of NoSQL, nothing to change mostly**_

If you want to have large amount of data (**_Exists better, faster way?_**). Just save the data in another table and tie the TOSId & TOSSessionKey with you. This way you may perform analytics on complex and very large data sets.

**Comment by JStika** [comment]
Very big thanks to you and for your willingness.:)

**Comment by saleemkce** [comment]
you are welcome.

And closing since the feature is supported built-in and it's just clarification.
